import { Toast } from "../components/ui/toast";
import "./globals.css";
import { AuthProvider } from "@/app/context/AuthContext";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          {children}
          <Toast />
        </body>
      </AuthProvider>
    </html>
  );
}
